[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leveldb = "0.8.6"
rpassword = "7.2.0"
rusqlite = "0.29.0"
tokio = { version = "1.28.1", features = ["full"] }
